/* eslint-disable max-len */

export const CURRENCIES_SYMBOLS = [
    { name: 'OANDA:AUD_CAD', title: 'AUD/CAD', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/aud.svg', imgBottom: 'server/constants/icons/currency/cad.svg' },
    { name: 'OANDA:AUD_CHF', title: 'AUD/CHF', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/aud.svg', imgBottom: '/server/constants/icons/currency/chf.svg' },
    { name: 'OANDA:AUD_JPY', title: 'AUD/JPY', leverage: 100, lotVolume: 1000, imgTop: '/server/constants/icons/currency/aud.svg', imgBottom: '/server/constants/icons/currency/jpy.svg' },
    { name: 'OANDA:AUD_NZD', title: 'AUD/NZD', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/aud.svg', imgBottom: '/server/constants/icons/currency/nzd.svg' },
    { name: 'OANDA:AUD_USD', title: 'AUD/USD', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/aud.svg', imgBottom: '/server/constants/icons/currency/usd.svg' },
    { name: 'OANDA:EUR_AUD', title: 'EUR/AUD', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/eur.svg', imgBottom: '/server/constants/icons/currency/aud.svg' },
    { name: 'OANDA:EUR_CHF', title: 'EUR/CHF', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/eur.svg', imgBottom: '/server/constants/icons/currency/chf.svg' },
    { name: 'OANDA:EUR_GBP', title: 'EUR/GBP', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/eur.svg', imgBottom: '/server/constants/icons/currency/gbp.svg' },
    { name: 'OANDA:EUR_JPY', title: 'EUR/JPY', leverage: 100, lotVolume: 1000, imgTop: '/server/constants/icons/currency/eur.svg', imgBottom: '/server/constants/icons/currency/jpy.svg' },
    { name: 'OANDA:EUR_USD', title: 'EUR/USD', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/eur.svg', imgBottom: '/server/constants/icons/currency/usd.svg' },
    { name: 'OANDA:GBP_AUD', title: 'GBP/AUD', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/gbp.svg', imgBottom: '/server/constants/icons/currency/aud.svg' },
    { name: 'OANDA:GBP_CAD', title: 'GBP/CAD', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/gbp.svg', imgBottom: 'server/constants/icons/currency/cad.svg' },
    { name: 'OANDA:GBP_CHF', title: 'GBP/CHF', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/gbp.svg', imgBottom: '/server/constants/icons/currency/chf.svg' },
    { name: 'OANDA:GBP_JPY', title: 'GBP/JPY', leverage: 100, lotVolume: 1000, imgTop: '/server/constants/icons/currency/gbp.svg', imgBottom: '/server/constants/icons/currency/jpy.svg' },
    { name: 'OANDA:GBP_USD', title: 'GBP/USD', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/gbp.svg', imgBottom: '/server/constants/icons/currency/usd.svg' },
    { name: 'OANDA:NZD_CAD', title: 'NZD/CAD', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/nzd.svg', imgBottom: 'server/constants/icons/currency/cad.svg' },
    { name: 'OANDA:NZD_CHF', title: 'NZD/CHF', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/nzd.svg', imgBottom: '/server/constants/icons/currency/chf.svg' },
    { name: 'OANDA:NZD_JPY', title: 'NZD/JPY', leverage: 100, lotVolume: 1000, imgTop: '/server/constants/icons/currency/nzd.svg', imgBottom: '/server/constants/icons/currency/jpy.svg' },
    { name: 'OANDA:NZD_USD', title: 'NZD/USD', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/nzd.svg', imgBottom: '/server/constants/icons/currency/usd.svg' },
    { name: 'OANDA:USD_CAD', title: 'USD/CAD', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/usd.svg', imgBottom: 'server/constants/icons/currency/cad.svg' },
    { name: 'OANDA:USD_CHF', title: 'USD/CHF', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/usd.svg', imgBottom: '/server/constants/icons/currency/chf.svg' },
    { name: 'OANDA:USD_JPY', title: 'USD/JPY', leverage: 100, lotVolume: 1000, imgTop: '/server/constants/icons/currency/usd.svg', imgBottom: '/server/constants/icons/currency/jpy.svg' },
    { name: 'OANDA:EUR_CAD', title: 'EUR/CAD', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/eur.svg', imgBottom: '/server/constants/icons/currency/cad.svg' },
    { name: 'OANDA:USD_DKK', title: 'USD/DKK', leverage: 600, lotVolume: 100000, imgTop: '/server/constants/icons/currency/usd.svg', imgBottom: '/server/constants/icons/currency/dk.svg' },
    { name: 'OANDA:USD_MXN', title: 'USD/MXN', leverage: 2000, lotVolume: 100000, imgTop: '/server/constants/icons/currency/usd.svg', imgBottom: '/server/constants/icons/currency/mx.svg' },
    { name: 'OANDA:USD_NOK', title: 'USD/NOK', leverage: 600, lotVolume: 100000, imgTop: '/server/constants/icons/currency/usd.svg', imgBottom: '/server/constants/icons/currency/nok.svg' },
    { name: 'OANDA:USD_SEK', title: 'USD/SEK', leverage: 600, lotVolume: 100000, imgTop: '/server/constants/icons/currency/usd.svg', imgBottom: '/server/constants/icons/currency/sek.svg' },
    // { name: 'OANDA:USD_RUB', title: 'USD/RUB', leverage: 100, lotVolume: 1000, imgTop: '/server/constants/icons/currency/usd.svg', imgBottom: '/server/constants/icons/currency/ru.svg' }, api doesn`t exist
    // { name: 'OANDA:EUR_RUB', title: 'EUR/RUB', leverage: 100, lotVolume: 1000, imgTop: '/server/constants/icons/currency/eur.svg', imgBottom: '/server/constants/icons/currency/ru.svg' }, api doesn`t exist
    { name: 'OANDA:USD_SGD', title: 'USD/SGD', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/usd.svg', imgBottom: '/server/constants/icons/currency/sgd.svg' },
    { name: 'OANDA:EUR_SGD', title: 'EUR/SGD', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/eur.svg', imgBottom: '/server/constants/icons/currency/sgd.svg' },
    { name: 'OANDA:GBP_SGD', title: 'GBP/SGD', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/gbp.svg', imgBottom: '/server/constants/icons/currency/sgd.svg' },
    { name: 'OANDA:NZD_SGD', title: 'NZD/SGD', leverage: 100, lotVolume: 100000, imgTop: '/server/constants/icons/currency/nzd.svg', imgBottom: '/server/constants/icons/currency/sgd.svg' }
];

export const VALUES_SYMBOLS = [
    { name: 'OANDA:XAU_USD', title: 'Gold', leverage: 10, lotVolume: 100, imgAlone: '/server/constants/icons/values/gold.svg' },
    { name: 'OANDA:XAG_USD', title: 'Silver', leverage: 10, lotVolume: 1000, imgAlone: '/server/constants/icons/values/silver.svg' },
    { name: 'OANDA:WTICO_USD', title: 'West Texas Oil', leverage: 10, lotVolume: 1000, imgAlone: '/server/constants/icons/values/crudeoil.svg' },
    { name: 'OANDA:BCO_USD', title: 'Brent Crude Oil', leverage: 10, lotVolume: 1000, imgAlone: '/server/constants/icons/values/crudeoil.svg' },
    { name: 'OANDA:CORN_USD', title: 'Corn', leverage: 2, lotVolume: 1000, imgAlone: '/server/constants/icons/values/corn.svg' },
    { name: 'OANDA:SOYBN_USD', title: 'Soybeans', leverage: 2, lotVolume: 1000, imgAlone: '/server/constants/icons/values/sbean.svg' },
    // { name: 'OANDA:COFFEE_USD', title: 'Coffee', leverage: 10, lotVolume: 1000, imgAlone: '/server/constants/icons/values/coffe.svg' }, api doesn`t exist
    { name: 'OANDA:SUGAR_USD', title: 'Sugar', leverage: 50, lotVolume: 1000000, imgAlone: '/server/constants/icons/values/sugar.svg' }
    // { name: 'OANDA:COTTON_USD', title: 'Cotton', leverage: 10, lotVolume: 1000, imgAlone: '/server/constants/icons/values/cotton.svg' }, api doesn`t exist
];

export const COMPANY_SHARES_SYMBOLS = [
    { name: 'AAPL', title: 'Apple Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/apple.svg' },
    { name: 'AMZN', title: 'Amazon Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/amazon.svg' },
    { name: 'BA', title: 'Boeing Co/The', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/boeing.svg' },
    { name: 'BAC', title: 'Bank of America Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/empty.svg' }, // picture not found
    { name: 'DIS', title: 'Walt Disney Co/The', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/disney.svg' },
    { name: 'FB', title: 'Facebook Inc-class A', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/facebook.svg' },
    { name: 'GOOGL', title: 'Google Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/google.svg' },
    { name: 'JCPB', title: 'Jpmorgan Core', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/jpm.svg' },
    { name: 'CCF', title: 'Chase Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/empty.svg' }, // picture not found
    { name: 'KO', title: 'Coca-cola Co/The', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/coke.svg' },
    { name: 'MCD', title: 'Mcdonald\'s Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/mcdon.svg' },
    { name: 'MSFT', title: 'Microsoft Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/msft.svg' },
    { name: 'PM', title: 'Philip Morris International', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/pmi.svg' },
    { name: 'YNDX', title: 'Yandex', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/yandex.svg' },
    { name: 'NFLX', title: 'Netflix Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/netflix.svg' },
    { name: 'TSLA', title: 'Tesla Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/empty.svg' }, // picture not found
    { name: 'AA', title: 'Alcoa Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/alcoa.svg' },
    { name: 'AXP', title: 'American express Co', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/empty.svg' },
    { name: 'CAT', title: 'Caterpillar', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/cat.svg' },
    { name: 'CSCO', title: 'Cisco Systems Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/cisco.svg' },
    { name: 'CVX', title: 'Chevron', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/chevron.svg' },
    { name: 'EBAY', title: 'Ebay', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/ebay.svg' },
    { name: 'GE', title: 'General Electric CO', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/genelc.svg' },
    { name: 'NVDA', title: 'Nvidia', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/nvidia.svg' },
    { name: 'PEP', title: 'Pepsico Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/pepsico.svg' },
    { name: 'UBER', title: 'Uber Technologies Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/uber.svg' },
    { name: 'NKE', title: 'Nike Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/nike.svg' },
    { name: 'ADBE', title: 'Adobe Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/adobe.svg' },
    // { name: 'BMW', title: 'BMW', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/bmw.svg' }, api doesn`t exist
    { name: 'HPE', title: 'Hewlett Packard Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/hpack.svg' },
    { name: 'IBM', title: 'Intl Business Mashine Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/ibm.svg' },
    { name: 'INTC', title: 'Intel Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/intel.svg' },
    { name: 'JNJ', title: 'Johnson & Johnson', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/jnj.svg' },
    { name: 'JPM', title: 'JPMorgan Chase & Co', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/jpm.svg' },
    { name: 'MCO', title: 'Moodys Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/empty.svg' },
    { name: 'MMM', title: '3M Company', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/3m.svg' },
    { name: 'MO', title: 'Altria Group', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/empty.svg' },
    { name: 'PFE', title: 'Pfizer Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/pfizer.svg' },
    { name: 'PG', title: 'Procter & Gamble Co', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/pcg.svg' },
    { name: 'T', title: 'AT&T', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/att.svg' },
    { name: 'VZ', title: 'Verizon Communications Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/verizon.svg' },
    { name: 'WMT', title: 'Walmart Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/walmart.svg' },
    { name: 'XOM', title: 'Exxon Mobil Corm', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/exxm.svg' },
    { name: 'LMT', title: 'Lockheed Martin Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/empty.svg' },
    { name: 'BIDU', title: 'Baidu Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/baidu.svg' },
    { name: 'MANT', title: 'Mantech International Corp-A', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/mant.png' },
    { name: 'HOFT', title: 'Hooker Furniture Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/hoft.png' },
    { name: 'GBT', title: 'Global Blood Therapeutics In', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/gbt.png' },
    { name: 'SAFM', title: 'Sanderson Farms Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/safm.png' },
    { name: 'DNLI', title: 'Denali Therapeutics Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/dnli.png' },
    { name: 'OFIX', title: 'Orthofix Medical Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/ofix.png' },
    { name: 'SKYW', title: 'Skywest Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/skyw.png' },
    { name: 'CTSH', title: 'Cognizant Tech Solutions-A', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/ctsh.png' },
    { name: 'CSII', title: 'Cardiovascular Systems Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/csii.png' },
    { name: 'PATK', title: 'Patrick Industries Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/patik.png' },
    { name: 'MIME', title: 'Mimecast Ltd', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/mime.png' },
    { name: 'NMFC', title: 'New Mountain Finance Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/nmfc.png' },
    { name: 'DDOG', title: 'Datadog Inc-Class A', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/ddog.png' },
    { name: 'ALLK', title: 'Allakos Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/allk.png' },
    { name: 'PLMR', title: 'Palomar Holdings Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/plmr.png' },
    { name: 'INTU', title: 'Intuit Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/intu.png' },
    { name: 'FROG', title: 'Jfrog Ltd', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/frog.png' },
    { name: 'HUBG', title: 'Hub Group Inc-CL A', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/hubg.png' },
    { name: 'CENTA', title: 'Central Garden And Per CO-A', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/centa.png' },
    { name: 'INGN', title: 'Inogen Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/ingn.png' },
    { name: 'HZNP', title: 'Horizontal Therapeutics PLC', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/hznp.png' },
    { name: 'BBIO', title: 'Bridgebio Pharma Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/bbio.png' },
    { name: 'UTMD', title: 'Utah Medical Products Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/utmd.png' },
    { name: 'PFC', title: 'Premier Financial Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/pfc.png' },
    { name: 'ACCD', title: 'Accolade Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/accd.png' },
    { name: 'CSGS', title: 'CSG Systems Intl Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/csgs.png' },
    { name: 'MTCH', title: 'Macom technology solutions H', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/mtch.png' },
    { name: 'QADA', title: 'QAD Inc-A', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/qada.png' },
    { name: 'BBSI', title: 'Barret Business SVCS Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/bbsi.png' },
    { name: 'CERN', title: 'Cerner Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/cern.png' },
    { name: 'IOSP', title: 'Innospec Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/iosp.png' },
    { name: 'TSCO', title: 'Tractor Supply Company', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/tsco.png' },
    { name: 'ARQT', title: 'Arcutis Biotherapeutics Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/arqt.png' },
    { name: 'APOG', title: 'Apogee Enterprises Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/apog.png' },
    { name: 'BRKS', title: 'Brooks Automation Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/brks.png' },
    { name: 'CERT', title: 'Certara Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/cert.png' },
    { name: 'XONE', title: 'Exone Co', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/xone.png' },
    { name: 'ADI', title: 'Analog Devices Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/adi.png' },
    { name: 'MLHR', title: 'Herman Miller Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/mlhr.png' },
    { name: 'BYND', title: 'Beyond Meat Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/bynd.png' },
    { name: 'PFPT', title: 'Proofpoint Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/pfpt.png' },
    { name: 'AY', title: 'Atlantica Sustainable Infras', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/ay.png' },
    { name: 'FCFS', title: 'FirstCash Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/fcfs.png' },
    { name: 'VRNT', title: 'Verint Systems Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/vrnt.png' },
    { name: 'HQY', title: 'Healthequity Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/hqy.png' },
    { name: 'ZM', title: 'Zoom Video Communications-A', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/zm.png' },
    { name: 'TXG', title: '10X Genomics Inc - Class A', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/txg.png' },
    { name: 'SEIC', title: 'Sei Investments Company', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/seic.png' },
    { name: 'QCOM', title: 'Qualcomm Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/qcom.png' },
    { name: 'CRWD', title: 'Crowdstrike Holdings Inc-A', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/crwd.png' },
    { name: 'STLD', title: 'Steel Dynamics Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/stld.png' },
    { name: 'COHU', title: 'Cohu Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/cohu.png' },
    { name: 'CG', title: 'Carlyle Group Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/cg.png' },
    { name: 'CHCO', title: 'City Holdings Co', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/chco.png' },
    { name: 'SNBR', title: 'Sleep Number Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/snbr.png' },
    { name: 'MDLZ', title: 'Mondelez International Inc-A', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/mdlz.png' },
    { name: 'REPL', title: 'Replimune Group Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/repl.png' },
    { name: 'FLXS', title: 'Flexsteel INDS', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/flxs.png' },
    { name: 'TTEC', title: 'TTEC Holdings Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/ttec.png' },
    { name: 'GNTX', title: 'Gentex Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/gntx.png' },
    { name: 'PEBO', title: 'Peoples Bancorp Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/pebo.png' },
    { name: 'CRSR', title: 'Corsair Gaming Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/crsr.png' },
    { name: 'ALVR', title: 'Allovir Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/alvr.png' },
    { name: 'RNET', title: 'Rignet Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/rnet.png' },
    { name: 'QDEL', title: 'Quidel Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/qdel.png' },
    { name: 'NVCR', title: 'Novocure Ltd', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/nvcr.png' },
    { name: 'FFIN', title: 'First Finl Bankshares Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/ffin.png' },
    { name: 'PKOH', title: 'Park-Ohio Holdings Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/pkoh.png' },
    { name: 'GBCI', title: 'Clacier Bancorp Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/gbci.png' },
    { name: 'PDD', title: 'Pinduoduo Inc-Adrc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/pdd.png' },
    { name: 'IDCC', title: 'Interdigital Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/idcc.png' },
    { name: 'TRMB', title: 'Trimble Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/trmb.png' },
    { name: 'EQIX', title: 'Equinix Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/eqix.png' },
    { name: 'DXCM', title: 'Platinum', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/platinum.png' },
    { name: 'KHC', title: 'Kraft Heinz Co', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/khc.png' },
    { name: 'CAC', title: 'Camden National Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/cac.png' },
    { name: 'SBNY', title: 'Signature Bank', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/sbny.png' },
    { name: 'OKTA', title: 'Okta Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/okta.png' },
    { name: 'EHTH', title: 'Ehealth Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/ehth.png' },
    { name: 'FLIR', title: 'Flir Systems Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/flir.png' },
    { name: 'TCOM', title: 'Trip.com Group Ltd', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/tcom.png' },
    { name: 'EYE', title: 'National Vision Holdings Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/eye.png' },
    { name: 'AZPN', title: 'Aspen Technology Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/azpn.png' },
    { name: 'GABC', title: 'German American Bancorp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/gabc.png' },
    { name: 'MGNI', title: 'Magnite Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/mgni.png' },
    { name: 'NDSN', title: 'Nordson Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/ndsn.png' },
    { name: 'TECH', title: 'Bio-techne Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/tech.png' },
    { name: 'UMBF', title: 'UMB financial Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/umbf.png' },
    { name: 'HURN', title: 'Huron Consulting Group Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/hurn.png' },
    { name: 'VIE', title: 'Viela Bio Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/vie.png' },
    { name: 'WABC', title: 'Westamerica Bancorporation', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/wabc.png' },
    { name: 'ACAD', title: 'Acadia Pharmaceuticals Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/acad.png' },
    { name: 'ADUS', title: 'Addus Homecare Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/adus.png' },
    { name: 'XP', title: 'XP Inc-Class A', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/xp.png' },
    { name: 'RNST', title: 'Renasant Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/rnst.png' },
    { name: 'OSIS', title: 'OSI Systems In', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/osis.png' },
    { name: 'SMCI', title: 'Super Micro Computer Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/smci.png' },
    { name: 'LYFT', title: 'Lyft Inc-A', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/lyft.png' },
    { name: 'PCTY', title: 'Paylocity Holding Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/pcty.png' },
    { name: 'FANG', title: 'Diamondback Energy Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/fang.png' },
    { name: 'RAVN', title: 'Raven Industries Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/ravn.png' },
    { name: 'AMWD', title: 'American Woodmark Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/amwd.png' },
    { name: 'FRME', title: 'First Merchants Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/frme.png' },
    { name: 'YORW', title: 'York Water Co', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/yorw.png' },
    { name: 'WING', title: 'Wingstop Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/wingstop.png' },
    { name: 'JRVR', title: 'James River Group Holdings', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/jrvr.png' },
    { name: 'KNSL', title: 'Kinsale Capital Group Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/knsl.png' },
    { name: 'WMG', title: 'Warner Music Group Corp-Cl A', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/wmg.png' },
    { name: 'LOB', title: 'Live Oak Bancshares Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/lob.png' },
    { name: 'SHEN', title: 'Shenandoah Telecommunication', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/shen.png' },
    { name: 'FIZZ', title: 'National Beverage Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/fizz.png' },
    { name: 'CNXN', title: 'Pc Connection Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/cnxn.png' },
    { name: 'LGIH', title: 'Lgi Homes Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/lgih.png' },
    { name: 'UCTT', title: 'Ultra Clean Holdings Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/uctt.png' },
    { name: 'DCT', title: 'Duck Creek Technologies Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/dct.png' },
    { name: 'JACK', title: 'Jack In the Box Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/jack.png' },
    { name: 'NTRS', title: 'Northern Trust Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/ntrs.png' },
    { name: 'TCBI', title: 'Texas Capital Banchares Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/tcbi.png' },
    { name: 'FRPH', title: 'FRP Holdings Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/frph.png' },
    { name: 'WTRE', title: 'Watford Holdings Ltd', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/wtre.png' },
    { name: 'WSFS', title: 'WSFS Financial Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/wsfs.png' },
    { name: 'RARE', title: 'Ultaragenyx Pharmaceutical In', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/rare.png' },
    { name: 'MXIM', title: 'Maxim Integrated Products', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/mxim.png' },
    { name: 'NBIX', title: 'Neurocrine Biosciences Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/nbix.png' },
    { name: 'ARCE', title: 'Arco Platform Ltd-Class A', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/arce.png' },
    { name: 'LKQ', title: 'LKQ Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/lkq.png' },
    { name: 'KDP', title: 'Keurig Dr Pepper Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/kdp.png' },
    { name: 'CORE', title: 'Core-Mark Holding Co Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/core.png' },
    { name: 'TWST', title: 'Twist Bioscience Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/twst.png' },
    { name: 'BRKR', title: 'Bruiker Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/brkr.png' },
    { name: 'MATW', title: 'Matthews Intl Corp-Class A', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/matw.png' },
    { name: 'CWST', title: 'Casella Waste Systems Inc-A', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/cwst.png' },
    { name: 'ARWR', title: 'Arrowhead Pharmaceuticals In', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/arwr.png' },
    { name: 'NTRA', title: 'Natera Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/ntra.png' },
    { name: 'EAR', title: 'Eargo Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/ear.png' },
    { name: 'UHAL', title: 'Amerco', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/uhal.png' },
    { name: 'MDGL', title: 'Madrigal Pharmaceuticals Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/mdgl.png' },
    { name: 'PPD', title: 'PPD Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/ppd.png' },
    { name: 'DCBO', title: 'Docebo Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/dcbo.png' },
    { name: 'BKNG', title: 'Booking Holdings Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/bkng.png' },
    { name: 'RCKY', title: 'Rocky Brands Inc', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/rcky.png' },
    { name: 'CDW', title: 'CDW Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/cdw.png' },
    { name: 'PODD', title: 'Insuler Corp', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/podd.png' },
    { name: 'HLNE', title: 'Hamilton Lane Inc-Class A', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/hlne.png' },
    { name: 'TW', title: 'Tradeweb Markets Inc-Class A', leverage: 5, lotVolume: 100, imgAlone: '/server/constants/icons/shares/tw.png' }
];

export const INDICES_SYMBOLS = [
    { name: 'JPXN', title: 'ISHARES JPX-NIKKEI 400 ETF', leverage: 100, lotVolume: 50, imgAlone: '/server/constants/icons/indices/nikkei.svg' },
    { name: '^NDX', title: 'Nasdaq-100', leverage: 100, lotVolume: 50, imgAlone: '/server/constants/icons/indices/nasdaq.svg' },
    { name: 'FDNI', title: 'FIRST TRUST DOW JONES INTL', leverage: 100, lotVolume: 50, imgAlone: '/server/constants/icons/indices/dow.svg' },
    { name: '^XU100', title: 'BIST100', leverage: 100, lotVolume: 50, imgAlone: '/server/constants/icons/indices/empty.svg' },
    { name: '^DJI', title: 'DOW', leverage: 100, lotVolume: 50, imgAlone: '/server/constants/icons/indices/dow.svg' },
    { name: 'DX', title: 'ICE USD', leverage: 100, lotVolume: 50, imgAlone: '/server/constants/icons/indices/iceusd.svg' },
    { name: '^VIX', title: 'VOL.SP500', leverage: 100, lotVolume: 50, imgAlone: '/server/constants/icons/indices/volsp500.svg' },
    { name: '^HSI', title: 'HANG SENG', leverage: 100, lotVolume: 50, imgAlone: '/server/constants/icons/indices/hang_seng.svg' }
];

export const CRYPTO_CURRENCIES_SYMBOLS = [
    { name: 'BINANCE:BTCUSDT', title: 'BTC/USD', leverage: 5, lotVolume: 5, imgTop: '/server/constants/icons/crypto/btc.svg', imgBottom: '/server/constants/icons/currency/usd.svg' },
    { name: 'BINANCE:ETHUSDT', title: 'ETH/USD', leverage: 10, lotVolume: 100, imgTop: '/server/constants/icons/crypto/eth.svg', imgBottom: '/server/constants/icons/currency/usd.svg' },
    { name: 'BINANCE:LTCUSDT', title: 'LTC/USD', leverage: 5, lotVolume: 100, imgTop: '/server/constants/icons/crypto/ltc.svg', imgBottom: '/server/constants/icons/currency/usd.svg' },

    { name: 'BINANCE:XRPUSDT', title: 'XRP/USD', leverage: 10, lotVolume: 100000, imgTop: '/server/constants/icons/crypto/xrp.svg', imgBottom: '/server/constants/icons/currency/usd.svg' },
    // { name: 'BINANCE:DSHUUSD', title: 'DSHU/USD', leverage: 5, lotVolume: 100, imgTop: '/server/constants/icons/crypto/dsh.svg', imgBottom: '/server/constants/icons/currency/usd.svg' }, api doesn`t exist
    // { name: 'BINANCE:XMRUSD', title: 'XMR/USD', leverage: 5, lotVolume: 100, imgTop: '/server/constants/icons/crypto/xmr.svg', imgBottom: '/server/constants/icons/currency/usd.svg' }, api doesn`t exist
    // { name: 'BINANCE:BTGUSD', title: 'BTG/USD', leverage: 5, lotVolume: 100, imgTop: '/server/constants/icons/crypto/btg.svg', imgBottom: '/server/constants/icons/currency/usd.svg' }, api doesn`t exist
    { name: 'BINANCE:TRXUSDT', title: 'TRX/USD', leverage: 10, lotVolume: 1000000, imgTop: '/server/constants/icons/crypto/trx.svg', imgBottom: '/server/constants/icons/currency/usd.svg' },
    { name: 'BINANCE:ETCUSDT', title: 'ETC/USD', leverage: 5, lotVolume: 1000, imgTop: '/server/constants/icons/crypto/etc.svg', imgBottom: '/server/constants/icons/currency/usd.svg' },
    // { name: 'BINANCE:GNTUSD', title: 'GNT/USD', leverage: 5, lotVolume: 100, imgTop: '/server/constants/icons/crypto/gnt.svg', imgBottom: '/server/constants/icons/currency/usd.svg' }, api doesn`t exist
    // { name: 'BINANCE:QTMUSD', title: 'QTM/USD', leverage: 5, lotVolume: 100, imgTop: '/server/constants/icons/crypto/qtm.svg', imgBottom: '/server/constants/icons/currency/usd.svg' }, api doesn`t exist
    { name: 'BINANCE:XEMUSDT', title: 'XEM/USD', leverage: 10, lotVolume: 1000000, imgTop: '/server/constants/icons/crypto/xem.svg', imgBottom: '/server/constants/icons/currency/usd.svg' },
    // { name: 'BINANCE:XVGUSD', title: 'XVG/USD', leverage: 5, lotVolume: 100, imgTop: '/server/constants/icons/crypto/xvg.svg', imgBottom: '/server/constants/icons/currency/usd.svg' }, api doesn`t exist
    { name: 'BINANCE:BCHBTC', title: 'BCH/BTC', leverage: 10, lotVolume: 1000000, imgTop: '/server/constants/icons/crypto/bch.svg', imgBottom: '/server/constants/icons/crypto/btc.svg' },
    { name: 'BINANCE:ETHBTC', title: 'ETH/BTC', leverage: 10, lotVolume: 1000000, imgTop: '/server/constants/icons/crypto/eth.svg', imgBottom: '/server/constants/icons/crypto/btc.svg' },
    { name: 'BINANCE:ETHBTC', title: 'ETH/BTC', leverage: 10, lotVolume: 1000000, imgTop: '/server/constants/icons/crypto/eth.svg', imgBottom: '/server/constants/icons/crypto/btc.svg' },
    { name: 'BINANCE:XMRBTC', title: 'XMR/BTC', leverage: 10, lotVolume: 1000000, imgTop: '/server/constants/icons/crypto/xmr.svg', imgBottom: '/server/constants/icons/crypto/btc.svg' },
    // { name: 'BINANCE:BCHETH', title: 'BCH/ETH', leverage: 5, lotVolume: 100, imgTop: '/server/constants/icons/crypto/bch.svg', imgBottom: '/server/constants/icons/crypto/eth.svg' }, api doesn`t exist
    { name: 'BINANCE:GNTETH', title: 'GNT/ETH', leverage: 10, lotVolume: 1000000, imgTop: '/server/constants/icons/crypto/gnt.svg', imgBottom: '/server/constants/icons/crypto/eth.svg' },
    { name: 'BINANCE:BTCRUB', title: 'BTC/RUB', leverage: 100, lotVolume: 0.07, imgTop: '/server/constants/icons/crypto/btc.svg', imgBottom: '/server/constants/icons/crypto/ru.svg' },
    { name: 'BINANCE:BTCEUR', title: 'BTC/EUR', leverage: 5, lotVolume: 5, imgTop: '/server/constants/icons/crypto/btc.svg', imgBottom: '/server/constants/icons/currency/eur.svg' },
    // { name: 'BINANCE:BCHRUB', title: 'BCH/RUB', leverage: 5, lotVolume: 100, imgTop: '/server/constants/icons/crypto/bch.svg', imgBottom: '/server/constants/icons/crypto/ru.svg' }, api doesn`t exist
    { name: 'BINANCE:ETHEUR', title: 'ETH/EUR', leverage: 100, lotVolume: 100, imgTop: '/server/constants/icons/crypto/eth.svg', imgBottom: '/server/constants/icons/currency/eur.svg' }
    // { name: 'BINANCE:DSHRUB', title: 'DSH/RUB', leverage: 5, lotVolume: 100, imgTop: '/server/constants/icons/crypto/dsh.svg', imgBottom: '/server/constants/icons/crypto/ru.svg' }, api doesn`t exist
    // { name: 'BINANCE:DSHEUR', title: 'DSH/EUR', leverage: 5, lotVolume: 100, imgTop: '/server/constants/icons/crypto/dsh.svg', imgBottom: '/server/constants/icons/currency/eur.svg' }, api doesn`t exist
];

export const CHART_SYMBOL_GROUPS = [
    { id: 'crypto', img: '/src/apps/client/ui/components/AssetsButton/images/bitcoin.svg', title: 'Криптовалюты', symbols: CRYPTO_CURRENCIES_SYMBOLS },
    { id: 'currencies', img: '/src/apps/client/ui/components/AssetsButton/images/currencies.svg', title: 'Валюты', symbols: CURRENCIES_SYMBOLS },
    { id: 'products', img: '/src/apps/client/ui/components/AssetsButton/images/production.svg', title: 'Товары', symbols: VALUES_SYMBOLS },
    { id: 'shares', img: '/src/apps/client/ui/components/AssetsButton/images/shares.svg', title: 'Акции', symbols: COMPANY_SHARES_SYMBOLS },
    { id: 'indices', img: '/src/apps/client/ui/components/AssetsButton/images/index.svg', title: 'Индексы', symbols: INDICES_SYMBOLS }
];

export const CHART_SYMBOL_INFO_MAP = {
    ...CHART_SYMBOL_GROUPS.reduce((result, group) => {
        const groupResult = group.symbols.reduce((result, symbol) => {
            return {
                ...result,
                [symbol.name]: {
                    ...symbol,
                    groupId: group.id
                }
            };
        }, {});

        return {
            ...result,
            ...groupResult
        };
    }, {})
};
